### ISSUE TITLE
Filename is wrong in README.md

### ISSUE THREAD

**Issue by mobluse** [guidol70/RunCPM_VGA32#3]
In README.md this filename is wrong: `./RunCPM_VGA32_v6_1_24072023_0x8000_0x8000.bin`

I flashed it on Raspberry Pi using (as one line):
`python3 /home/pi/esptool/esptool.py --chip esp32 --port /dev/ttyACM0 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0xe000 ./boot_app0_0xe000.bin 0x1000 ./bootloader_qio_80m_0x1000.bin 0x10000 ./RunCPM_VGA32_v6_1_24072023_0x10000.bin 0x8000 ./RunCPM_VGA32_v6_1_24072023_0x8000.bin`

**Comment by guidol70** [comment]
Corrected - added two sample command-line files.
One for VGA32 and one for the Olimex ESP32-SBC-FabGL ;)

Thanks for the information
